(require(tidyverse) && packageVersion("tidyverse") >= "1.2.1") || install.packages("tidyverse")
require(shiny) || install.packages("shiny")
require(shinyjs) || install.packages("shinyjs")
require(RCurl) || install.packages("RCurl")
require(markdown) || install.packages("markdown")
